# Generated by Django 4.1.4 on 2022-12-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='description',
            field=models.CharField(default=None, max_length=200000),
        ),
    ]
