
runtime: python

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
#entrypoint: gunicorn -b :$PORT MovieCollection.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
# the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  SECRET_KEY: 'django-insecure-wvau-69av7*6ug*am)wiz2n3eua5cjld9p5i$+fnwevse+7ihr'
  DEBUG: 'False' # always False for deployment

# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
  DB_HOST: nth-rarity-372710:northamerica-northeast1:fathimanafeesa
  DB_PORT: 5432 # PostgreSQL port
  DB_NAME: mc_database
  DB_USER: postgres # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: aydin


handlers:
- url: /static
  static_dir: static

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: nth-rarity-372710:northamerica-northeast1:fathimanafeesa

runtime_config:

  python_version: 3 # enter your Python version BASE ONLY here. Enter 2 for 2.7.9 or 3 for 3.6.4

readiness_check:

  app_start_timeout_sec: 1000